GET http://localhost:3000/todos/

###

GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/?category=WORK&status=DONE

###
GET http://localhost:3000/todos/?category=HOME

###
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###
GET http://localhost:3000/todos/?search_q=Buy

###
GET http://localhost:3000/todos/4/

###
GET http://localhost:3000/agenda/?date=2021-02-22
 
###
POST http://localhost:3000/todos/ 
content-type: Application/json

{
  "id": 10,
  "todo": "Buy a car",
  "priority": "HIGH",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###
PUT http://localhost:3000/todos/9/ 
content-type: Application/json

{
  "status": "DONE"
}

###
PUT http://localhost:3000/todos/9/ 
content-type: Application/json

{
  "priority": "HIGH"
}

###
PUT http://localhost:3000/todos/9/ 
content-type: Application/json

{
  "todo": "Clean the garden"
}

###
PUT http://localhost:3000/todos/9/ 
content-type: Application/json

{
  "category": "LEARNING"
}

###
PUT http://localhost:3000/todos/9/ 
content-type: Application/json

{
  "dueDate": "2021-01-12"
}

###
DELETE http://localhost:3000/todos/15/ 
